reloading configuration succeeded
reloading zones succeeded
validating @0x7fcdc80530b0: mirror.as24220.net A: no valid signature found
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 10.0.0.52#53
no longer listening on ::1#53
exiting
zone 0.in-addr.arpa/IN: loaded serial 0
zone 0.0.10.in-addr.arpa/IN: loaded serial 3
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone henogez.com/IN: loaded serial 3
zone localhost/IN: loaded serial 0
managed-keys-zone ./IN: loaded serial 197
running
zone henogez.com/IN: sending notifies (serial 3)
zone 0.0.10.in-addr.arpa/IN: sending notifies (serial 3)
received control channel command 'reload'
loading configuration from '/etc/named.conf'
reading built-in trusted keys from file '/etc/named.iscdlv.key'
using default UDP/IPv4 port range: [1024, 65535]
using default UDP/IPv6 port range: [1024, 65535]
sizing zone task pool based on 6 zones
using built-in DLV key for view _default
Warning: 'empty-zones-enable/disable-empty-zone' not set: disabling RFC 1918 empty zones
reloading configuration succeeded
reloading zones succeeded
managed-keys-zone ./IN: Unable to fetch DNSKEY set 'dlv.isc.org': operation canceled
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 10.0.0.52#53
no longer listening on ::1#53
exiting
zone 0.in-addr.arpa/IN: loaded serial 0
zone 0.0.10.in-addr.arpa/IN: loaded serial 3
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone henogez.com/IN: loaded serial 3
zone localhost/IN: loaded serial 0
managed-keys-zone ./IN: loaded serial 211
running
zone henogez.com/IN: sending notifies (serial 3)
zone 0.0.10.in-addr.arpa/IN: sending notifies (serial 3)
received control channel command 'reload'
loading configuration from '/etc/named.conf'
reading built-in trusted keys from file '/etc/named.iscdlv.key'
using default UDP/IPv4 port range: [1024, 65535]
using default UDP/IPv6 port range: [1024, 65535]
sizing zone task pool based on 6 zones
using built-in DLV key for view _default
Warning: 'empty-zones-enable/disable-empty-zone' not set: disabling RFC 1918 empty zones
reloading configuration succeeded
reloading zones succeeded
managed-keys-zone ./IN: Unable to fetch DNSKEY set 'dlv.isc.org': operation canceled
validating @0x7fdaf1170040: mirror.as24220.net A: no valid signature found
validating @0x7fdaf0c05880: linux.mirrors.es.net A: no valid signature found
error (unexpected RCODE SERVFAIL) resolving 'mirror.vcu.edu/A/IN': 128.143.2.7#53
error (unexpected RCODE REFUSED) resolving 'archive.linux.duke.edu/A/IN': 204.63.227.77#53
validating @0x7fdaf0fecc40: mirror.as24220.net A: no valid signature found
zone 0.in-addr.arpa/IN: loaded serial 0
zone 0.0.10.in-addr.arpa/IN: loaded serial 3
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone henogez.com/IN: loaded serial 3
zone localhost/IN: loaded serial 0
managed-keys-zone ./IN: loaded serial 229
running
zone 0.0.10.in-addr.arpa/IN: sending notifies (serial 3)
zone henogez.com/IN: sending notifies (serial 3)
received control channel command 'reload'
loading configuration from '/etc/named.conf'
reading built-in trusted keys from file '/etc/named.iscdlv.key'
using default UDP/IPv4 port range: [1024, 65535]
using default UDP/IPv6 port range: [1024, 65535]
sizing zone task pool based on 6 zones
using built-in DLV key for view _default
Warning: 'empty-zones-enable/disable-empty-zone' not set: disabling RFC 1918 empty zones
reloading configuration succeeded
reloading zones succeeded
error (broken trust chain) resolving 'mirror.as24220.net/A/IN': 2402:d800:0:1::5#53
validating @0x7fc40cfea880: mirror.as24220.net A: no valid signature found
validating @0x7fc40d07e640: linux.mirrors.es.net A: no valid signature found
validating @0x7fc40cfea880: mirror.as24220.net A: no valid signature found
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 10.0.0.52#53
no longer listening on ::1#53
exiting
zone 0.in-addr.arpa/IN: loaded serial 0
zone 0.0.10.in-addr.arpa/IN: loaded serial 3
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone henogez.com/IN: loaded serial 3
zone localhost/IN: loaded serial 0
managed-keys-zone ./IN: loaded serial 235
running
zone 0.0.10.in-addr.arpa/IN: sending notifies (serial 3)
zone henogez.com/IN: sending notifies (serial 3)
received control channel command 'reload'
loading configuration from '/etc/named.conf'
reading built-in trusted keys from file '/etc/named.iscdlv.key'
using default UDP/IPv4 port range: [1024, 65535]
using default UDP/IPv6 port range: [1024, 65535]
sizing zone task pool based on 6 zones
using built-in DLV key for view _default
Warning: 'empty-zones-enable/disable-empty-zone' not set: disabling RFC 1918 empty zones
reloading configuration succeeded
reloading zones succeeded
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 10.0.0.52#53
no longer listening on ::1#53
exiting
zone 0.in-addr.arpa/IN: loaded serial 0
zone 0.0.10.in-addr.arpa/IN: loaded serial 3
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone henogez.com/IN: loaded serial 3
zone localhost/IN: loaded serial 0
managed-keys-zone ./IN: loaded serial 237
running
zone 0.0.10.in-addr.arpa/IN: sending notifies (serial 3)
zone henogez.com/IN: sending notifies (serial 3)
